In [6]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # data visualization
import seaborn as sns # statistical data visualization
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
%matplotlib inline
from sklearn.model_selection import train_test_split


#source : https://www.kaggle.com/code/prashant111/random-forest-classifier-tutorial

In [ ]:
pip install --upgrade scikit-learn

In [ ]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/cesu_datasets.csv')

# Create a symbolic link
!ln -s /content/gdrive/My\ Drive/ /mydrive

# List the contents of your Google Drive
!ls /mydrive

In [38]:
data = '/content/cesu_datasets.csv'
df = pd.read_csv(data)
# view dimensions of dataset
print('Datasets:', df.shape)

Datasets: (199952, 15)


CATEGORICAL

In [27]:

# Load the CSV data
data = pd.read_csv('/content/cesu_datasets.csv')

# Define custom encoding dictionaries for each categorical column
encoding_dict_kasarian = {'Lalake': 0, 'Babae': 1}
encoding_dict_edad= {'17-below': 0, '18-24': 1, '25-34': 2, '35-44': 3, '45-54': 4, '55-64': 5, '65-Above': 6 }
encoding_dict_antas = {'Hindi nakapagtapos ng Elementarya':0, 'Elementarya':1, 'Hindi nakapagtapos ng Sekundarya':2, 'Sekundarya':3, 'Kolehiyo':4, 'Hindi nakapagtapos ng Kolehiyo':5, 'Masters Degree':6, 'Doctorate Degree':7, 'Hindi nakapag-aral':8}  # Define your categories and values
encoding_dict_uri = {'May Trabaho': 1, 'Walang Trabaho': 0}  # Define your categories and values
#encoding_dict_program = {'Literacy': 0, 'Socio-economic': 1, 'Environmental Stewardship': 2, 'Health and Wellness': 3, 'Cultural Enhancement': 4, 'Values Formation': 5, 'Disaster Management': 6, 'Gender and Development': 7}  # Define your categories and values


# Apply custom encoding to the categorical columns
data['Kasarian'] = data['Kasarian'].map(encoding_dict_kasarian)
data['Edad'] = data['Edad'].map(encoding_dict_edad)
data['Antas na tinapos'] = data['Antas na tinapos'].map(encoding_dict_antas)
data['Uri ng trabaho'] = data['Uri ng trabaho'].map(encoding_dict_uri)
#data['Program'] = data['Program'].map(encoding_dict_program)

# Split the data into training and testing sets
X = data.drop(['Program'], axis=1)  # Features
y = data['Program']  # Target variable

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)


In [28]:
X_train.head()

Kasarian  Edad  Antas na tinapos  Uri ng trabaho  \
25178          1     1                 3               1   
183559         0     6                 7               1   
42266          1     2                 5               0   
99930          0     3                 7               1   
147446         0     5                 4               0   

        Serbisyong Pangedukasyon  Pagsasanay Pangkabuhayan (Livelihood)  \
25178                          0                                      0   
183559                         0                                      0   
42266                          1                                      0   
99930                          1                                      0   
147446                         1                                      0   

        Pagtatanim  Serbisyong Pangkalusugan  Serbisyong Dental  \
25178            0                         0                  0   
183559           0                         0                  0   
42266            1                         1                  0   
99930            1                         1                  1   
147446           1                         0                  1   

        Kaalamang Pangkultura  Values Formation at Moral Recovery  \
25178                       1                                   0   
183559                      0                                   1   
42266                       1                                   0   
99930                       0                                   1   
147446                      0                                   0   

        Ayudang Pagkain (Food Assistance)  Pagrerecycle  \
25178                                   0             1   
183559                                  0             0   
42266                                   0             1   
99930                                   0             1   
147446                                  1             1   

        Pagsasanay Ukol sa Teknolohiya  
25178                                0  
183559                               0  
42266                                0  
99930                                0  
147446                               0

In [29]:
X_test.head()

Kasarian  Edad  Antas na tinapos  Uri ng trabaho  \
153954         1     5                 3               1   
120352         1     4                 3               1   
809            1     0                 0               0   
52630          1     2                 0               1   
195564         0     6                 3               1   

        Serbisyong Pangedukasyon  Pagsasanay Pangkabuhayan (Livelihood)  \
153954                         1                                      0   
120352                         0                                      0   
809                            1                                      0   
52630                          0                                      1   
195564                         1                                      0   

        Pagtatanim  Serbisyong Pangkalusugan  Serbisyong Dental  \
153954           0                         0                  1   
120352           1                         1                  0   
809              0                         0                  1   
52630            1                         0                  1   
195564           1                         1                  0   

        Kaalamang Pangkultura  Values Formation at Moral Recovery  \
153954                      1                                   0   
120352                      1                                   0   
809                         1                                   1   
52630                       0                                   1   
195564                      1                                   1   

        Ayudang Pagkain (Food Assistance)  Pagrerecycle  \
153954                                  0             1   
120352                                  0             0   
809                                     0             1   
52630                                   0             1   
195564                                  1             0   

        Pagsasanay Ukol sa Teknolohiya  
153954                               0  
120352                               0  
809                                  0  
52630                                0  
195564                               0

In [30]:
# check data types in X_train

X_train.dtypes

Kasarian                                 int64
Edad                                     int64
Antas na tinapos                         int64
Uri ng trabaho                           int64
Serbisyong Pangedukasyon                 int64
Pagsasanay Pangkabuhayan (Livelihood)    int64
Pagtatanim                               int64
Serbisyong Pangkalusugan                 int64
Serbisyong Dental                        int64
Kaalamang Pangkultura                    int64
Values Formation at Moral Recovery       int64
Ayudang Pagkain (Food Assistance)        int64
Pagrerecycle                             int64
Pagsasanay Ukol sa Teknolohiya           int64
dtype: object

In [31]:
# check the shape of X_train and X_test

X_train.shape, X_test.shape

((133967, 14), (65985, 14))

In [32]:
col_names = ['Kasarian', 'Edad', 'Antas na tinapos', 'Uri ng trabaho', 'Serbisyong Pangedukasyon', 'Pagsasanay Pangkabuhayan (Livelihood)', 'Pagtatanim', 'Serbisyong Pangkalusugan', 'Serbisyong Dental', 'Kaalamang Pangkultura', 'Values Formation at Moral Recovery', 'Ayudang Pagkain (Food Assistance)', 'Pagrerecycle', 'Pagsasanay Ukol sa Teknolohiya', 'Program']
df.columns = col_names
col_names
df.head()

Kasarian      Edad                   Antas na tinapos  Uri ng trabaho  \
0    Babae  17-below  Hindi nakapagtapos ng Elementarya  Walang Trabaho   
1    Babae  17-below  Hindi nakapagtapos ng Elementarya  Walang Trabaho   
2    Babae  17-below  Hindi nakapagtapos ng Elementarya  Walang Trabaho   
3    Babae  17-below  Hindi nakapagtapos ng Elementarya  Walang Trabaho   
4    Babae  17-below  Hindi nakapagtapos ng Elementarya  Walang Trabaho   

   Serbisyong Pangedukasyon  Pagsasanay Pangkabuhayan (Livelihood)  \
0                         1                                      0   
1                         0                                      1   
2                         0                                      0   
3                         0                                      0   
4                         0                                      0   

   Pagtatanim  Serbisyong Pangkalusugan  Serbisyong Dental  \
0           0                         0                  0   
1           0                         0                  0   
2           1                         0                  0   
3           0                         1                  0   
4           0                         0                  1   

   Kaalamang Pangkultura  Values Formation at Moral Recovery  \
0                      0                                   0   
1                      0                                   0   
2                      0                                   0   
3                      0                                   0   
4                      0                                   0   

   Ayudang Pagkain (Food Assistance)  Pagrerecycle  \
0                                  0             0   
1                                  0             0   
2                                  0             0   
3                                  0             0   
4                                  0             0   

   Pagsasanay Ukol sa Teknolohiya                    Program  
0                               0                   Literacy  
1                               0             Socio-economic  
2                               0  Environmental Stewardship  
3                               0        Health and Wellness  
4                               0        Health and Wellness

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score


rfc = RandomForestClassifier(n_estimators=100, random_state=42)

rfc.fit(X_train, y_train)


y_pred = rfc.predict(X_test)

# Check accuracy score
accuracy = accuracy_score(y_test, y_pred)
print('Model accuracy score with 100 decision-trees: {0:0.4f}'.format(accuracy))


Model accuracy score with 100 decision-trees: 0.9952


In [34]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Display additional evaluation metrics
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))



Accuracy: 1.00
                           precision    recall  f1-score   support

     Cultural Enhancement       0.97      0.93      0.95       227
      Disaster Management       0.16      0.15      0.16        72
Environmental Stewardship       0.99      0.99      0.99      6132
       Gender Development       0.26      0.23      0.24        78
      Health and Wellness       1.00      1.00      1.00     24923
                 Literacy       1.00      1.00      1.00     15615
           Socio-economic       1.00      1.00      1.00     18533
         Values Formation       0.87      0.87      0.87       405

                 accuracy                           1.00     65985
                macro avg       0.78      0.77      0.78     65985
             weighted avg       1.00      1.00      1.00     65985

[[  212     0     0    14     0     1     0     0]
 [    0    11    38     0     0    23     0     0]
 [    0    31  6100     0     0     1     0     0]
 [    6     0     0    18

Export the model

In [35]:
import joblib
# Assuming 'rfc' is your trained Random Forest Classifier
joblib.dump(rfc, 'trained_modelCESU5.pkl')

['trained_modelCESU5.pkl']

In [36]:
from google.colab import files
files.download('trained_modelCESU5.pkl')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
# Print the Confusion Matrix and slice it into four pieces
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix\n\n', cm)

Confusion matrix

 [[  9   0   0   0   0   0   0   0]
 [  0   6   0   0   0   1   0   0]
 [  0   0  37   0   0   0   0   0]
 [  0   0   0   6   0   0   0   0]
 [  0   0   0   0  55   0   0   0]
 [  0   1   0   0   0 362   1   0]
 [  0   0   0   0   0   0 255   0]
 [  0   0   0   1   0   0   0  21]]


# **Multiple combination of datasets**

In [3]:
import itertools
import csv

combinations = list(itertools.product([0, 1], repeat=10))

csv_file = "cesu65-Above.csv"

with open(csv_file, mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow([
        "Kasarian",
        "Edad",
        "Antas na tinapos",
        "Uri ng trabaho",
        "Serbisyong Pangedukasyon",
        "Pagsasanay Pangkabuhayan (Livelihood)",
        "Pagtatanim",
        "Serbisyong Pangkalusugan",
        "Serbisyong Dental",
        "Kaalamang Pangkultura",
        "Values Formation at Moral Recovery",
        "Ayudang Pagkain (Food Assistance)",
        "Pagrerecycle",
        "Pagsasanay Ukol sa Teknolohiya",
        "Program"
    ])

    constant_values = {
        "edad": "65-Above",
        "trabaho": "Walang Trabaho",
    }

    gender_values = ["Babae", "Lalake"]
    education_values = [
        "Hindi nakapagtapos ng Elementarya",
        "Elementarya",
        "Hindi nakapagtapos ng Sekundarya",
        "Sekundarya",
        "Hindi nakapagtapos ng Kolehiyo",
        "Kolehiyo",
        "Masters Degree",
        "Doctorate Degree",
    ]

    for kasarian_value in gender_values:
        for antas_value in education_values:
            constant_values["kasarian"] = kasarian_value
            constant_values["antas"] = antas_value

            for combo in combinations:
                (serbisyong_pangedukasyon, pagsasanay_pangkabuhayan, pagtatanim,
                serbisyong_pangkalusugan, dental, kultura, values, ayudang_pagkain,
                recycle, teknolohiya) = combo

                if serbisyong_pangkalusugan == 1:
                    predict_value = "Health and Wellness"
                elif ayudang_pagkain == 1:
                    predict_value = "Socio-economic"
                elif dental == 1:
                    predict_value = "Health and Wellness"
                elif pagsasanay_pangkabuhayan == 1:
                    predict_value = "Socio-economic"
                elif teknolohiya == 1:
                    predict_value = "Literacy"
                elif serbisyong_pangedukasyon == 1:
                    predict_value = "Literacy"
                elif pagtatanim == 1:
                    predict_value = "Environmental Stewardship"
                elif recycle == 1:
                    predict_value = "Environmental Stewardship"
                elif kultura == 1:
                    predict_value = "Cultural Enhancement"
                elif values == 1:
                    predict_value = "Values Formation"
                else:
                    predict_value = "Health and Wellness"

                # Append the constant values and binary attribute values to the CSV file
                writer.writerow([constant_values["kasarian"], constant_values["edad"],
                                 constant_values["antas"], constant_values["trabaho"]] + list(combo) + [predict_value])

print("CSV file created: " + csv_file)


CSV file created: cesu65-Above.csv


# May Trabaho

In [4]:
import itertools
import csv

combinations = list(itertools.product([0, 1], repeat=10))

csv_file = "cesu65-Above-Maytrabaho.csv"

with open(csv_file, mode="w", newline="") as file:
    writer = csv.writer(file)
    writer.writerow([
        "Kasarian",
        "Edad",
        "Antas na tinapos",
        "Uri ng trabaho",
        "Serbisyong Pangedukasyon",
        "Pagsasanay Pangkabuhayan (Livelihood)",
        "Pagtatanim",
        "Serbisyong Pangkalusugan",
        "Serbisyong Dental",
        "Kaalamang Pangkultura",
        "Values Formation at Moral Recovery",
        "Ayudang Pagkain (Food Assistance)",
        "Pagrerecycle",
        "Pagsasanay Ukol sa Teknolohiya",
        "Program"
    ])

    constant_values = {
        "edad": "65-Above",
        "trabaho": "May Trabaho",
    }

    gender_values = ["Babae", "Lalake"]
    education_values = [
        "Hindi nakapagtapos ng Elementarya",
        "Elementarya",
        "Hindi nakapagtapos ng Sekundarya",
        "Sekundarya",
        "Hindi nakapagtapos ng Kolehiyo",
        "Kolehiyo",
        "Masters Degree",
        "Doctorate Degree",
    ]

    for kasarian_value in gender_values:
        for antas_value in education_values:
            constant_values["kasarian"] = kasarian_value
            constant_values["antas"] = antas_value

            for combo in combinations:
                (serbisyong_pangedukasyon, pagsasanay_pangkabuhayan, pagtatanim,
                serbisyong_pangkalusugan, dental, kultura, values, ayudang_pagkain,
                recycle, teknolohiya) = combo

                if serbisyong_pangkalusugan == 1:
                    predict_value = "Health and Wellness"
                elif teknolohiya == 1:
                    predict_value = "Literacy"
                elif dental == 1:
                    predict_value = "Health and Wellness"
                elif serbisyong_pangedukasyon == 1:
                    predict_value = "Literacy"
                elif ayudang_pagkain == 1:
                    predict_value = "Socio-economic"
                elif pagtatanim == 1:
                    predict_value = "Environmental Stewardship"
                elif recycle == 1:
                    predict_value = "Environmental Stewardship"
                elif pagsasanay_pangkabuhayan == 1:
                    predict_value = "Socio-economic"
                elif values == 1:
                    predict_value = "Values Formation"
                elif kultura == 1:
                    predict_value = "Cultural Enhancement"
                else:
                    predict_value = "Health and Wellness"

                # Append the constant values and binary attribute values to the CSV file
                writer.writerow([constant_values["kasarian"], constant_values["edad"],
                                 constant_values["antas"], constant_values["trabaho"]] + list(combo) + [predict_value])

print("CSV file created: " + csv_file)


CSV file created: cesu65-Above-Maytrabaho.csv
